projects_dir: projects_to_analyze
repos_file: test_runs/cases/ok_smoke_realish/repos.txt
cycles_file: test_runs/cases/ok_smoke_realish/cycles_to_analyze.txt
results_root: test_runs/cases/ok_smoke_realish/results
experiment_id: sim_ok_smoke_realish

llm:
  base_url: "http://127.0.0.1:8012/v1"
  api_key: "placeholder"
  model_raw: "dummy"

openhands:
  image: "docker.all-hands.dev/all-hands-ai/openhands:0.59"
  runtime_image: "docker.all-hands.dev/all-hands-ai/runtime:0.59-nikolaik"
  max_iters: 2
  commit_message: "Refactor: break dependency cycle"

modes:
  - id: explain_multiAgent
    params:
      orchestrator: v1_four_agents
      refactor_prompt_variant: default
