projects_dir: projects_to_analyze
repos_file: test_runs/cases/ok_smoke_fail_early_openhands_llm/repos.txt
cycles_file: test_runs/cases/ok_smoke_fail_early_openhands_llm/cycles_to_analyze.txt
results_root: test_runs/cases/ok_smoke_fail_early_openhands_llm/results
experiment_id: sim_ok_smoke_fail_early_openhands_llm

policy:
  delete_refactor_branches_after_metrics: true

llm:
  base_url: "http://127.0.0.1:8012/v1"
  api_key: "placeholder"
  model_raw: "dummy"
  context_length: 32768

openhands:
  runtime_image: "docker.openhands.dev/openhands/runtime:1.4-nikolaik"
  max_iters: 3
  commit_message: "Refactor: break dependency cycle"

modes:
  - id: explain_multiAgent
    params:
      orchestrator: multi_agent
      edge_variant: E0
      synthesizer_variant: S0
      auxiliary_agent: none
