projects_dir: test_runs/mocks/projects
repos_file: test_runs/cases/ok_smoke_minimal/repos.txt
cycles_file: test_runs/cases/ok_smoke_minimal/cycles_to_analyze.txt
results_root: test_runs/cases/ok_smoke_minimal/results
experiment_id: sim_ok_smoke_minimal

llm:
  base_url: "http://127.0.0.1:8012/v1"
  api_key: "placeholder"
  model_raw: "dummy"

openhands:
  image: "docker.all-hands.dev/all-hands-ai/openhands:0.59"
  runtime_image: "docker.all-hands.dev/all-hands-ai/runtime:0.59-nikolaik"
  max_iters: 1
  commit_message: "Refactor: break dependency cycle"

modes:
  - id: no_explain
    params:
      orchestrator: minimal
